class LoginJsonResponse {
  String? login;
  String? userName;
  String? username;
  String? password;
  String? confirmPassword;
  String? submit;
  String? name;
  String? lastName;
  String? verificationCode;
  String? select;
  String? disable;
  String? number;
  String? loginText;
  String? do1;
  String? signUp;
  String? forgetPass;
  String? signUpText1;
  String? signUpText2;
  String? signUpText3;
  String? loginWithGoogle;
  String? forgetPassHeader;
  String? newPassword;
  String? resetPass;
  String? iNVALIDACCOUNT;
  String? invalidVerificationCode;
  String? dUPPLICATEACCOUNT;
  String? acceptRules1;
  String? acceptRules2;
  String? back;
  String? rule1;
  String? ruleAccept;
  String? rule2;
  String? cellNumber;
  String? email;

  LoginJsonResponse.fromJson(Map<String, dynamic> json) {
    login = json['login'];
    userName = json['userName'];
    username = json['username'];
    password = json['password'];
    confirmPassword = json['confirmPassword'];
    submit = json['submit'];
    name = json['name'];
    lastName = json['lastName'];
    verificationCode = json['verificationCode'];
    select = json['select'];
    disable = json['disable'];
    number = json['number'];
    loginText = json['loginText'];
    do1 = json['do'];
    signUp = json['signUp'];
    forgetPass = json['forgetPass'];
    signUpText1 = json['signUpText1'];
    signUpText2 = json['signUpText2'];
    signUpText3 = json['signUpText3'];
    loginWithGoogle = json['loginWithGoogle'];
    forgetPassHeader = json['forgetPassHeader'];
    newPassword = json['newPassword'];
    resetPass = json['resetPass'];
    iNVALIDACCOUNT = json['INVALID_ACCOUNT'];
    invalidVerificationCode = json['invalidVerificationCode'];
    dUPPLICATEACCOUNT = json['DUPPLICATE_ACCOUNT'];
    acceptRules1 = json['acceptRules1'];
    acceptRules2 = json['acceptRules2'];
    back = json['back'];
    rule1 = json['rule1'];
    ruleAccept = json['ruleAccept'];
    rule2 = json['rule2'];
    cellNumber = json['cellNumber'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['login'] = this.login;
    data['userName'] = this.userName;
    data['username'] = this.username;
    data['password'] = this.password;
    data['confirmPassword'] = this.confirmPassword;
    data['submit'] = this.submit;
    data['name'] = this.name;
    data['lastName'] = this.lastName;
    data['verificationCode'] = this.verificationCode;
    data['select'] = this.select;
    data['disable'] = this.disable;
    data['number'] = this.number;
    data['loginText'] = this.loginText;
    data['do'] = this.do1;
    data['signUp'] = this.signUp;
    data['forgetPass'] = this.forgetPass;
    data['signUpText1'] = this.signUpText1;
    data['signUpText2'] = this.signUpText2;
    data['signUpText3'] = this.signUpText3;
    data['loginWithGoogle'] = this.loginWithGoogle;
    data['forgetPassHeader'] = this.forgetPassHeader;
    data['newPassword'] = this.newPassword;
    data['resetPass'] = this.resetPass;
    data['INVALID_ACCOUNT'] = this.iNVALIDACCOUNT;
    data['invalidVerificationCode'] = this.invalidVerificationCode;
    data['DUPPLICATE_ACCOUNT'] = this.dUPPLICATEACCOUNT;
    data['acceptRules1'] = this.acceptRules1;
    data['acceptRules2'] = this.acceptRules2;
    data['back'] = this.back;
    data['rule1'] = this.rule1;
    data['ruleAccept'] = this.ruleAccept;
    data['rule2'] = this.rule2;
    data['cellNumber'] = this.cellNumber;
    data['email'] = this.email;
    return data;
  }
}
