// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZp9JQ-PqL6voRvhcwEM-57BjTJaEaEQ',
    appId: '1:445634122479:web:c0a4b9d38a84bf7ab2411a',
    messagingSenderId: '445634122479',
    projectId: 'sigmatec-d86ad',
    authDomain: 'sigmatec-d86ad.firebaseapp.com',
    storageBucket: 'sigmatec-d86ad.firebasestorage.app',
    measurementId: 'G-F0E20L9PE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmiyjYlSx2FMFy-JqH6zyAXNxgbqBzFKc',
    appId: '1:445634122479:android:fa5ec9ff9856a571b2411a',
    messagingSenderId: '445634122479',
    projectId: 'sigmatec-d86ad',
    storageBucket: 'sigmatec-d86ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ9b7OX_rZT4ton-IZtinFjV9OfHaqnjE',
    appId: '1:445634122479:ios:b9f66c6fe9739f76b2411a',
    messagingSenderId: '445634122479',
    projectId: 'sigmatec-d86ad',
    storageBucket: 'sigmatec-d86ad.firebasestorage.app',
    iosBundleId: 'ir.sigmatec.sigma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ9b7OX_rZT4ton-IZtinFjV9OfHaqnjE',
    appId: '1:445634122479:ios:ba18299377db0537b2411a',
    messagingSenderId: '445634122479',
    projectId: 'sigmatec-d86ad',
    storageBucket: 'sigmatec-d86ad.firebasestorage.app',
    iosBundleId: 'com.example.sigma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvZp9JQ-PqL6voRvhcwEM-57BjTJaEaEQ',
    appId: '1:445634122479:web:39a5f0464e8572a8b2411a',
    messagingSenderId: '445634122479',
    projectId: 'sigmatec-d86ad',
    authDomain: 'sigmatec-d86ad.firebaseapp.com',
    storageBucket: 'sigmatec-d86ad.firebasestorage.app',
    measurementId: 'G-46QLT3BBC6',
  );

}